config/routes.rb
Rails.application.routes.draw do

  root to: 'landing#index'
  get :about, to: 'static_pages#about'

  mount ActionCable.server => '/cable'

  resources :users, only: [:new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :edit, :create, :update, :destroy]

  post :upvote, to: 'votes#upvote'
  post :downvote, to: 'votes#downvote'

  resources :topics, except: [:show] do
    resources :posts, except: [:show] do
      resources :comments, except: [:show]
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  def should_generate_new_friendly_id?
    new_record?
  end
end

# Or...

class Article < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :history
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  mount_uploader :image, ImageUploader
  validates :body, length: { minimum: 20 }, presence: true
  belongs_to :user
  enum role: [:user, :moderator, :admin]
  paginates_per 6
  has_many :votes

  def total_votes
    votes.pluck(:value).sum
  end

# Vote.where(comment_id: comment_id).sum(:value)
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :topic
  mount_uploader :image, ImageUploader
  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  belongs_to :user
  paginates_per 6

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts
  validates :title, length: { minimum: 3 }, presence: true
  validates :description, length: { minimum: 10 }, presence: true
  paginates_per 6
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
 has_many :topics
 has_many :posts
 has_many :comments
 has_secure_password
 validates :email, uniqueness: true
 enum role: [:user, :moderator, :admin]
 has_many :votes
 extend FriendlyId
 friendly_id :username, use: :slugged
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_messages_helper.rb
module FlashMessagesHelper

  def display_message(value)

    return content_tag(:p, value) unless value.kind_of?(Array)

    content_tag :ul do
      value.collect { |message| content_tag(:li, message, class: 'list-styling') }.join.html_safe
    end
  end
end

app/views/comments/_comment.html.erb
<div class="comment <%=extra_class%>" data-id="<%= comment.id %>">
  <%= image_tag comment.image.thumb %>

  <h5 class="font-feature-2">
    <%= comment.body %>
  </h5>

  <div class="buttons">
     <% if comment.user == current_user %>
     <%= link_to edit_topic_post_comment_path(post.topic, post, comment), remote: true do%>
      <%= fa_icon "edit 2x", class: "btn btn-success btn-lg" %>
      <% end %>
    <% end %>

    <% if comment.user == current_user || current_user&.admin? || current_user&.moderator? %>
    <%= link_to topic_post_comment_path(post.topic,post, comment), method: :delete, remote: true do %>
      <%= fa_icon "trash 2x", class: "btn btn-danger btn-lg" %>
      <% end %>
    <% end %>
  </div>

  <div class="vote">
    <span>total:</span>
    <span class="voting-score"><%= comment.total_votes %></span>
    <%= link_to upvote_path(comment_id: comment.id), method: :post, remote: true do %>
      <%= fa_icon "thumbs-o-up 2x" %>
    <% end %>
    <%= link_to downvote_path(comment_id: comment.id), method: :post, remote: true do %>
    <%= fa_icon "thumbs-o-down 2x" %>
    <% end %>
  </div>

</div>

app/views/comments/_create_form.html.erb
<div class="text-center margin-create">

<%= form_for(comment, url: topic_post_comments_path(post.topic, post), method: :post, authenticity_token: true, remote: true, html: { id: "comment-create-form", multipart: true }) do |f| %>
  <h1 class="text-center">
    Create Comment
  </h1>

    <div class="form-group" "preview-image">
      <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>
      <h4> <%= f.label :text_field, "Body" %> </h4>
      <%= f.text_field :body, id: "comment_body_field", class: 'form-control' %>
    </div>

    <div class="form-group text-center">
      <%= f.submit "Create Comment", class: "btn btn-success btn-lg" %>
    </div>



  <% end %>

</div>

app/views/comments/_edit_form.html.erb
<div class="text-center margin-create2" id="comments-update">

<%= form_for(comment, url: topic_post_comment_path(topic, post, comment), authenticity_token: true, remote: true, html: { id: "comment-update-form", multipart: true}) do |f| %>
  <h1 class="text-center">
    Create Comment
  </h1>

  <div class="form-group">
      <h4 class="text-center"> Post Image </h4>
      <div id="preview-image">
        <% if @comment.image? %>
          <%= image_tag @comment.image, class: "img-settings img-responsive center-block" %>
        <% end %>
      </div>
    </div>

  <div class="form-group">
    <%= f.file_field :image, id: "comment_image_field", class: 'form-control image-uploader' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "comment_description_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Update Comment", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/comments/create.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

<% if @comment.persisted? %>
$('#comments').append("<%=j render partial: 'comments/comment', locals: { comment: @comment, post: @comment.post, topic: @topic, extra_class: '' } %>")
$('#comments-form-container').html("<%=j render partial: 'comments/create_form', locals: { comment: @new_comment, post: @post } %>")
<% end %>

app/views/comments/destroy.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

$('.comment[data-id=<%=@comment.id%>.id%>]').remove();

<% if @comment.persisted? %>
$('#comments-delete').replaceall("<%=j render partial: 'comment', locals: { comment: @comment, post: @comment.post, topic: @topic } %>")
<% end %>

app/views/comments/edit.html.erb
<div class="text-center margin-create2">

<%= form_for(@comment, url: topic_post_comment_path(@topic, @post, @comment), html: { id: "comment-update-form" }) do |f| %>
  <h1 class="text-center">
    Create Comment
  </h1>

  <div class="form-group">
      <h4 class="text-center"> Post Image </h4>
      <div id="preview-image">
        <% if @comment.image? %>
          <%= image_tag @comment.image, class: "img-settings img-responsive center-block" %>
        <% end %>
      </div>
    </div>

  <div class="form-group">
    <%= f.file_field :image, id: "comment_image_field", class: 'form-control image-uploader' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "comment_description_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Update Comment", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/comments/edit.js.erb
$('.comment[data-id=<%=@comment.id%>]').html("<%=j render partial: 'edit_form', locals: { comment: @comment, post: @post, topic: @topic } %>")

app/views/comments/index.html.erb
<div class="comments index" data-id="<%= @post.id %>">

  <h1>Comments</h1>

  <div id="comments">
    <% @comments.each do |comment| %>
    <div class="text-center">
    <%= render partial: "comment", locals: { comment: comment, post: @post, topic: @topic, extra_class: '' } %>
  </div>
  <% end %>
  </div>

  <%= paginate @comments %>
  <%= page_entries_info @comments %>

  <div id="comments-form-container">
    <%= render partial: "create_form", locals: { comment: @comment, post: @post } %>
  </div>

</div>

app/views/comments/update.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

<% if @comment.persisted? %>
$('#comments-update').replaceWith("<%=j render partial: 'comment', locals: { comment: @comment, post: @comment.post, topic: @topic, extra_class: '' } %>")
<% end %>

app/views/landing/index.html.erb
<div class="landing">
      <div class="background">
      <div class="content">
        <h1 style="color: white; font-size: 40px;">Hello World</h1>
      </div>
    </div>

    <div class="background-2">
      <div class="content">
        <h1 style="font-family:Times New Roman; color: grey;font-size: 24px">Where cool people meet </h1>
      </div>
    </div>

    <section class="features-container text-center">
     <h1 style="color: black; font-size: 21px">Let's Explore</h1>

      <div class="features text-center">
        <div class="feature">
          <%= fa_icon 'globe 4x', class:"fa-pulse" %>
          <h5> International Hub </h5>
        </div>

          <div class="feature">
            <%= fa_icon 'universal-access 4x', class:"fa-pulse" %>
            <h5> Universal Assistant </h5>
          </div>

          <div class="feature">
            <%= fa_icon 'google-plus-official 4x',class:"fa-pulse" %>
            <h5> Online Communities </h5>
          </div>

          <div class="feature">
            <%= fa_icon 'spinner 4x',class:"fa-pulse" %>
            <h5> 24/7 Suport </h5>
          </div>
      </div>
    </section>

    <section class="features-container2 text-center">
    <!-- <div class="photos"> -->

      <div class="features-image">
        <div class="blue-layout">
          <div class="content-hover">
            <h3 style="color: black; font-size: 24px"> Kick'in In!</h3>
          </div>
        </div>
        <%= image_tag "ruby.gif", class:"image-setting" %>
      </div>

      <div class="features-image">
        <div class="blue-layout">
          <div class="content-hover">
            <h3> Hop'in In!</h3>
          </div>
        </div>
        <%= image_tag "book.gif",class:"image-setting" %>
      </div>

      <div class="features-image">
        <div class="blue-layout">
          <div class="content-hover">
            <h3> Fly'in Out!</h3>
          </div>
        </div>
        <%= image_tag "no.gif",class:"image-setting" %>
      </div>

      <div class="features-image">
        <div class="blue-layout">
          <div class="content-hover">
            <h3> Chill'in Out!</h3>
          </div>
        </div>
        <%= image_tag "world.gif",class:"image-setting" %>
      </div>
    </section>

    <section class="contact-container">
      <div class="contact text-center">
        <h1 style="font-family:Times New Roman; color: white; font-size: 24px; justify-content: center">
          Let's Chat!
        </h1>
        <hr class="short-underline">
        <p> Honestly you gonna see da world!.</p>
        </div>

      <div class="contact2 text-center">
        <div class="feature">
          <%= fa_icon 'phone'%>
          <h5> Touch In </h5>
          </div>
          <div class="feature">
            <%= fa_icon 'envelope'%>
            <h5> Drop In </h5>
          </div>
        </div>


    </section>

    <div class="flex-parent"> <!-- display: flex; align-items:center -->
      <div class="flex-child"> <!-- flex: 0 0 300px -->
      <div class="flex-child">
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Magicforums</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <% if current_user && (current_user.admin? || current_user.moderator?) %>
  <meta name="wizardwonka">
  <% end %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div id="header">
    <%= render partial: 'partials/header' %>
  </div>

  <div id="flash-messages-container">
    <%= render partial: "partials/flash_messages" %>
  </div>
  <%= render partial: "partials/login" %>
  <%= render partial: "partials/register" %>

  <%= yield %>
</body>
</html>

app/views/partials/_flash_messages.html.erb
<div id="flash-messages-container">
  <% flash.each do |k,v| %>
  <section class="flash-messages">
    <div class="alert alert-<%=k%>">
      <button type="button" class="close" data-dismiss="alert">
        &times;
      </button>
      <div class="message">
        <%= display_message(v) %>
      </div>
    </div>
  </section>
<% end %>
</div>

app/views/partials/_header.html.erb
<div class="header">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "MagicForums", root_path, class: "navbar-brand" %>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-dropdown" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse" id="header-dropdown">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "About", about_path %></li>
              <% if current_page?(controller: 'topics' , action: 'index') %>
              <li><%= link_to "New Topic", new_topic_path %></li>
            <% else %>
              <li><%= link_to "Topics", topics_path %></li>
            <% end %>


          <% if current_user %>
          <li>
            <%= link_to current_user.username, edit_user_path(current_user), class: 'white shadowed link-styling' %>
          </li>

          <li>
            <%= link_to "Logout", session_path(current_user), method: :delete, class: 'white shadowed link-styling' %>
          </li>

          <% else %>

          <li>
            <!-- <%= link_to "Register", new_user_path, class: 'white shadowed link-styling' %> -->
            <a data-toggle="modal" data-target="#register" class="white shadowed link-styling">Register</a>
          </li>

          <li>
            <!-- <%= link_to "Login", new_session_path, class: 'white shadowed link-styling' %> -->
            <a data-toggle="modal" data-target="#login" class="white shadowed link-styling">login</a>
          </li>
          <% end %>
        </div>

      </div>
    </nav>
</div>

app/views/partials/_login.html.erb
<div class="modal fade" id="login">
   <div class="modal-dialog">
     <div class="modal-content">
       <div class="modal-body">
         <div class="text-center margin-create">

           <h1 class="text-center">
             Login
           </h1>

           <%= form_for(:user,url: sessions_path, html: { id: "user-create-form" })  do |f| %>


             <div class="form-group">
             <h4> <%= f.label :email %> </h4>
             <%= f.text_field :email, required: true, id: "user_field", class: 'form-control' %>
           </div>

           <div class="form-group">
             <h4> <%= f.label :password %> </h4>
             <%= f.password_field :password, id: "Password_field", class: 'form-control' %>
           </div>

           <div class="font-feature-new text-center">
             <%= f.submit "Login", class: "btn btn-success btn-lg" %>
             <%=link_to "Sign Up", new_user_path, class: "btn btn-info btn-lg" %>
             <%=link_to "Reset Password", new_password_reset_path, class: "btn btn-info btn-lg" %>
             <%=link_to "Back to topics", topics_path, class: "btn btn-info btn-lg" %>
           </div>


         <% end %>
         </div>

       </div>
     </div>
   </div>
 </div>

app/views/partials/_register.html.erb
<div class="modal fade" id="register">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">

        <div class="text-center margin-create">

          <%= form_for(:user,url: users_path, html: { id: "user-create-form" })  do |f| %>
          <h1 class="text-center">
            Welcome
          </h1>

          <div class="form-group">
            <h4> <%= f.label :username_field, "Username" %> </h4>
            <%= f.text_field :username, required: true, id: "username_field", class: 'form-control' %>
          </div>

          <div class="form-group">
            <h4> <%= f.label :email_field, "Email" %> </h4>
            <%= f.text_field :email, required: true, id: "email_field", class: 'form-control' %>
          </div>

          <div class="form-group">
            <h4> <%= f.label :password_field, "Password" %> </h4>
            <%= f.password_field :password, required: true, id: "Password_field", class: 'form-control' %>
          </div>

          <div class="form-group">
            <h4> <%= f.label :password_field, "Password Confirmation" %> </h4>
            <%= f.password_field :password_confirmation, required: true, id: "Password_field", class: 'form-control' %>
          </div>

          <div class="form-group text-center">
            <%= f.submit "Register", class: "btn btn-success btn-lg" %>
          </div>

          <!-- <div class="form-group text-center">
          <%= f.submit "Create", class: "btn btn-success btn-lg" %>
        </div> -->



        <% end %>

      </div>
    </div>
  </div>
</div>
</div>

app/views/password_resets/edit.html.erb
<div class="password-resets edit">
   <div class="content">
     <%= form_for(:user, url: password_reset_path(id: @token), method: :patch, html: { id: "user-set-new-password-form" }) do |f| %>
       <h1 class="white shadowed text-center">
         Set New Password
       </h1>

       <div class="form-group">
         <h4> <%= f.label :password_field, "Password", class: "white shadowed" %> </h4>
         <%= f.password_field :password, required: true,  id: 'user_password_field', class: 'form-control' %>
       </div>

       <div class="form-group text-center">
         <%= f.submit "Update my password!", class: "btn btn-primary btn-lg" %>
       </div>
     <% end %>
   </div>
 </div>

app/views/password_resets/new.html.erb
<div class="password-resets new">
  <div class="content">
    <%= form_for(:reset, url: password_resets_path, method: :post, html: { id: "user-reset-password-form" }) do |f| %>
      <h1 class="white shadowed text-center">
        Reset Password
      </h1>

      <div class="form-group">
        <h4> <%= f.label :email_field, "Email", class: "white shadowed" %> </h4>
        <%= f.email_field :email, required: true,  id: 'user_email_field', class: 'form-control' %>
      </div>

      <div class="form-group text-center">
        <%= f.submit "Reset my password!", class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_create_form.htm.erb
<div class="text-center margin-create">

  <%= form_for(@post,url: topic_posts_path(@topic, @post), remote: true, html: { id: "post-create-form" })  do |f| %>
  <h1 class="text-center">
    Create Post
  </h1>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "post_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "post_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Post", class: "btn btn-success btn-lg" %>
  </div>



<% end %>

</div>

app/views/posts/edit.html.erb
<div class="text-center margin-create2">

<%= form_for(@post, url: topic_post_path(@topic, @post), html: { id: "post-update-form" }) do |f| %>

  <h1 class="text-center">
    Edit Post
  </h1>

  <div class="form-group">
      <h4 class="text-center"> Post Image </h4>
      <div id="preview-image">
        <% if @post.image? %>
          <%= image_tag @post.image, class: "img-settings img-responsive center-block" %>
        <% end %>
      </div>
    </div>


<div class="form-group">
  <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>
</div>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "post_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "post_description_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Update Post", class: "btn btn-success btn-lg" %>
  </div>

<% end %>

app/views/posts/index.html.erb
<div class="a text-center">

  <h1>Posts</h1>

  <%= link_to "Add post", new_topic_post_path(@topic, @post) %>

  <% if @posts.any? %>


  <% @posts.each do |post| %>
  <%= render partial: "post", locals: { post: post, topic: @topic } %>
  <div class="text-center topic">
  <div class="">
      <h3 style="text-center"><%= post.title %></h3>
      <%= image_tag post.image.thumb %>
      <h5><%= post.body %></h5>
      <%= link_to "more info", topic_post_comments_path(post.topic, post) %>
      <%= link_to "Edit", edit_topic_post_path(@topic,post)%>
      <%= link_to "Delete", topic_post_path(@topic,post), method: :delete, data: { confirm: "Delete?" } %>

    </div>
  </div>
  <% end %>

  <% else %>

  <p>Nothing to see here</p>
  <p>
    No posts here. Create new post?
  </p>

  <% end %>


  <%= paginate @posts %>
  <%= page_entries_info @posts %>


</div>

app/views/posts/new.html.erb
<div class="text-center margin-create">

  <%= form_for(@post,url: topic_posts_path(@topic, @post), html: { id: "post-create-form" })  do |f| %>
  <h1 class="text-center">
    Create Post
  </h1>

  <div class="form-group">
    <h4 class="text-center"> Post Image </h4>
    <div id="preview-image">
      <%= image_tag "see.jpg", class: "img-settings img-responsive center-block" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "post_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "post_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Post", class: "btn btn-success btn-lg" %>
  </div>



<% end %>

</div>

app/views/static_page/about.html.erb
<div class="about">
  <div class="about-pic">
  <div class="content">
    <%= fa_icon 'circle-o  3x' %>
    <h1 style="color: white; opacity: 0.3; font-size: 40px"> Bit about me </h1>
  </div>

  <section class="meow text-center">
     <h1 style="color: black; font-size: 21px">lil secret bout me-ow!</h1>
     <hr class="short-underline" />

      <div class="intros text-center">

        <div class="intro">
          <%= image_tag "camera.gif",class:"profile-setting" %>
          <h5> Photo </h5>
        </div>

        <div class="intro">
          <%= image_tag "rainbow.gif",class:"profile-setting" %>
          <h5> Travel </h5>
        </div>

        <div class="intro">
          <%= image_tag "sf.jpg",class:"profile-setting" %>
          <h5> Online Communities </h5>
        </div>

        <h1 style="font-family:Times New Roman; color: white; font-size: 24px; justify-content: center">
          something about me blah !
        </h1>

        <%= link_to "https://www.facebook.com/" do %>
        <%= fa_icon 'facebook 4x' %>
        <%end%>

        <%= link_to "https://twitter.com/" do %>
        <%= fa_icon 'twitter 4x' %>
        <%end%>

        <%= link_to "https://www.instagram.com/" do %>
        <%= fa_icon 'instagram 4x' %>
        <%end%>

        <%= link_to "https://www.pinterest.com/" do %>
        <%= fa_icon 'pinterest 4x' %>
        <%end%>

      </div>

  </section>



</div>

app/views/static_pages/about.html.erb
<div class="about">
  <div class="about-pic">
    <div class="content">
      <%= fa_icon 'circle-o  3x' %>
      <h1 style="color: white; opacity: 0.7; font-size: 50px"> Bit about me </h1>
    </div>
  </div>

  <section class="meow text-center">
     <h1 style="color: black; font-size: 21px">lil secret bout me-ow!</h1>
     <hr class="short-underline" />

      <div class="intros text-center">

        <div class="intro">
          <%= image_tag "photo.jpg",class:"profile-setting" %>
          <h5> Photo </h5>
        </div>

        <div class="intro">
          <%= image_tag "bg.jpg",class:"profile-setting" %>
          <h5> Travel </h5>
        </div>

        <div class="intro">
          <%= image_tag "sf.jpg",class:"profile-setting" %>
          <h5> Online Communities </h5>
        </div>

        <div class="intro">
          <h1 style="font-family:Times New Roman; color: white; font-size: 24px; justify-content: center">
          something about me blah !
        </h1>

        <div class="intro">
          <%= link_to "https://www.facebook.com/" do %>
          <%= fa_icon 'facebook 2x' %>
        <%end%>

        <div class="intro">
          <%= link_to "https://twitter.com/" do %>
          <%= fa_icon 'twitter 2x' %>
        <%end%>

        <div class="intro">
          <%= link_to "https://www.instagram.com/" do %>
          <%= fa_icon 'instagram 2x' %>
        <%end%>

        <div class="intro-2">
          <%= link_to "https://www.pinterest.com/" do %>
          <%= fa_icon 'pinterest 2x' %>
        <%end%>



      </div>

  </section>



</div>

app/views/topics/edit.html.erb
<div class="text-center margin-create2">

<%= form_for(@topic, url: topic_path(@topic), html: { id: "topic-update-form" }) do |f| %>
  <h1 class="text-center">
    Create Topic
  </h1>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "topic_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Description" %> </h4>
    <%= f.text_field :description, id: "topic_description_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Update Topic", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/topics/index.html.erb
<div class="text-center">

  <h1>Topics</h1>

  <div class="topics">
  <% @topics.each do |topic| %>
  <div class="text-center topic">
    <div class="">
      <h3 style="text-center"><%= topic.title %></h3>
      <h5><%= topic.description %></h5>
      <%= link_to "more info", topic_posts_path(topic), :class => 'btn btn-warning btn-md'%>
      <%= link_to "Edit", edit_topic_path(topic)%>
      <%= link_to "Delete", topic_path(topic), method: :delete, data: { confirm: "Delete?" } %>
    </div>
  </div>
  <% end %>
  </div>
  <%= paginate @topics %>
  <%= page_entries_info @topics %>

</div>

app/views/topics/new.html.erb
<div class="text-center margin-create">

  <%= form_for(@topic, url: topics_path, html: { id: "topic-create-form" }) do |f| %>
  <h1 class="text-center">
    Create Topic
  </h1>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "topic_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Description" %> </h4>
    <%= f.text_field :description, id: "topic_description_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create Topic", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

</div>

app/views/users/edit.html.erb
<div class="text-center margin-create">

  <%= form_for(@user,url: user_path, html: { id: "user-create-form" })  do |f| %>
  <h1 class="text-center">
    Edit User
  </h1>

  <div class="form-group">
    <h4> <%= f.label :password_field, "Password" %> </h4>
    <%= f.password_field :password, required: true, id: "Password_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :password_field, "Password Confirmation" %> </h4>
    <%= f.password_field :password_confirmation, required: true, id: "Password_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Update", class: "btn btn-success btn-lg" %>
    <%= f.submit "Back", class: "btn btn-success btn-lg" %>
  </div>

  <% end %>
</div>